#pragma once

namespace mce
{
    enum VertexFieldType
    {
        VERTEX_FIELD_TYPE_UNKNOWN,
        VERTEX_FIELD_TYPE_SINT8,
        VERTEX_FIELD_TYPE_UINT8,
        VERTEX_FIELD_TYPE_SINT16,
        VERTEX_FIELD_TYPE_UINT16,
        VERTEX_FIELD_TYPE_SINT32,
        VERTEX_FIELD_TYPE_UINT32,
        VERTEX_FIELD_TYPE_FLOAT16,
        VERTEX_FIELD_TYPE_FLOAT32
    };
}